version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "shift-d"
      - "NTBBloodBath"
    commit-message:
      prefix: "chore(dependencies): "
