name: Build
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Build pnp
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --profile optimized
      - name: Upload pnp Linux binary
        uses: actions/upload-artifact@v2
        with:
          name: "pnp-linux-x86_64"
          path: "target/optimized/pnp"
          if-no-files-found: error
          retention-days: 7

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Build pnp
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --profile optimized
      - name: Upload pnp MacOS binary
        uses: actions/upload-artifact@v2
        with:
          name: "pnp-macos-x86_64"
          path: "target/optimized/pnp"
          if-no-files-found: error
          retention-days: 7

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Build pnp
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --profile optimized
      - name: Upload pnp Windows binary
        uses: actions/upload-artifact@v2
        with:
          name: "pnp-windows-x86_64.exe"
          path: "target\\optimized\\pnp.exe"
          if-no-files-found: error
          retention-days: 7
